### ISSUE TITLE
Running in Docker: TTY mode requires /dev/tty to be read/writable.

### ISSUE THREAD

**Issue by rasmuscnielsen** [spatie/laravel-horizon-watcher#12]
Hi 👋

I'm trying to spin up a Docker container running  `php artisan horizon:watch` as entrypoint command. 

```
    app-queue:
        build:
            context: .
            dockerfile: Dockerfile
        command: php artisan horizon:watch
        [...]
```

However, due to the `$this->horizonProcess->setTty(true)->setTimeout(null)` line, I get the following error:

```
app-queue_1  |    INFO  Starting Horizon and will restart it when any files change...  
app-queue_1  | 
app-queue_1  | 
app-queue_1  |    Symfony\Component\Process\Exception\RuntimeException 
app-queue_1  | 
app-queue_1  |   TTY mode requires /dev/tty to be read/writable.
```

Changing the line to `->setTty(false)` it runs without issues. 

I'm not 100% sure what purpose `->setTty(true)` serves, but would it be possible to make it configurable at the very least?

Thanks!
